### ISSUE TITLE
Aw, snap! We didn't get a username with your request.

### ISSUE THREAD

**Issue by vinayakumarr** [jvmancuso/DeepIDS#1]
Aw, snap! We didn't get a username with your request.

Don't have an account? https://plot.ly/api_signup

Questions? accounts@plot.ly
---------------------------------------------------------------------------
PlotlyError                               Traceback (most recent call last)
<ipython-input-42-395a97dc4516> in <module>()
      6              )
      7 figure = go.Figure(data = data, layout = layout)
----> 8 plt.iplot(figure, filename='tsne-scatter')

/home/vinay/securetensor/local/lib/python2.7/site-packages/plotly/plotly/plotly.pyc in iplot(figure_or_data, **plot_options)
    162         embed_options['height'] = str(embed_options['height']) + 'px'
    163 
--> 164     return tools.embed(url, **embed_options)
    165 
    166 
![untitled](https://user-images.githubusercontent.com/18217467/41203641-b55ae340-6cf7-11e8-9496-abb83de87433.png)

**Comment by jvmncs** [comment]
Plotly requires a free account/API key to use. See this page for more: https://plot.ly/python/getting-started/

**Comment by alfieraesmith** [comment]
This does not solve the issue. There is no reference to plotly api at  https://plot.ly/python/getting-started/

**Comment by jvmncs** [comment]
as mentioned in your error message, you need a plotly username with an API key.  https://plot.ly/api_signup will allow you to sign up for that
